package main.java.com.dnasequencing.gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class WelcomePanel extends JPanel implements ActionListener {
    private JTextArea welcomeTextArea;


    public WelcomePanel() {
        setLayout(new BorderLayout());
        JLabel label = new JLabel(" Welcome to my DNA Sequencing Application ");
        label.setHorizontalAlignment(SwingConstants.CENTER);

        welcomeTextArea = new JTextArea("""
                   _________________________________________________________________________
                   Thank you for choosing the DNA analysis application from Jakob Winkler. 
                   Below is a brief guide on how to use the application.
                   The last page also explains how the application works.\s
                   _________________________________________________________________________                                   
                   In the first step, you will be asked to select a file that is accessible on your computer. 
                   If the content of the *.txt file meets the criteria, the "Start Analyzation" button will be highlighted.
                   Click on it to start the analysis.
                   Now you can click through the various tabs and view the individual data generated by the analysis.
                   To load a new file, you must return to this page and click on the "Load File" button. \s
                """);
        welcomeTextArea.setEditable(false);
        welcomeTextArea.setLineWrap(true);

        add(label, BorderLayout.NORTH);
        add(welcomeTextArea, BorderLayout.CENTER);
    }

    @Override
    public void actionPerformed(ActionEvent e) {

    }
}
